export PATH=$PATH:/Users/cinaremir/.spicetify
eval "$(starship init zsh)"
export PATH="$HOME/.emacs.d/bin:$PATH"
alias fetch="fastfetch"
alias cat="bat"
alias tmacs="emacs --no-window-system"
alias numbers="btop"
alias spice="spicetify"
alias py="python3"
alias pip="pip3"
alias lgit="lazygit"
alias zumrut="cd ~/Documents/zumrutKitaplik"
alias zel="zellij"
alias zelswap="zellij --layout /Users/cinaremir/.config/zellij/layouts/tower.kdl"
eval "$(zoxide init zsh --cmd cd)"
export PATH="/Users/cinaremir/Library/Python/3.9/bin:$PATH"
alias ls="lsd"
